apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: nginx-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: nginx-lb
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - args:
        - --leader-elect
        - --leader-election-id=nginx-lb-operator
        ## Change image with image name
        image: "controller" #controller:latest
        imagePullPolicy: Always
        name: manager
        env:
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: WATCH_NAMESPACE
          value: "" #"nginx-ingress"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "nginx-lb-operator"
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: ANSIBLE_DEBUG_LOGS
          value: "False"
        - name: ANSIBLE_VERBOSITY_APPLICATION_LB_NGINX_COM
          value: "1"
        - name: WORKER_APPLICATION_LB_NGINX_COM
          value: "1"
        - name: ANSIBLE_VERBOSITY_CERTIFICATE_LB_NGINX_COM
          value: "1"
        - name: WORKER_CERTIFICATE_LB_NGINX_COM
          value: "1"
        - name: ANSIBLE_VERBOSITY_COMPONENT_LB_NGINX_COM
          value: "1"
        - name: WORKER_COMPONENT_LB_NGINX_COM
          value: "1"
        - name: ANSIBLE_VERBOSITY_CONTROLLER_LB_NGINX_COM
          value: "1"
        - name: WORKER_CONTROLLER_LB_NGINX_COM
          value: "1"
        - name: ANSIBLE_VERBOSITY_GATEWAY_LB_NGINX_COM
          value: "1"
        - name: WORKER_GATEWAY_LB_NGINX_COM
          value: "1"
        - name: ANSIBLE_VERBOSITY_DEPLOYMENT_APPS
          value: "1"
        - name: WORKER_DEPLOYMENT_APPS
          value: "1"
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6789
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6789
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 10m
            memory: 256Mi
      volumes:
        - name: runner
          emptyDir: {}
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
