---

    - name: Get the certificate from K8s Secret
      block:

      - name: Load the secret
        k8s_info:
          kind: Secret
          name: "{{ spec.secret }}"
          namespace: "{{ meta.namespace }}"
        register: cert

      - name: Set desiredState
        set_fact:
          desiredState:
            type: "{{ cert.resources.0.data.type | default('') | b64decode }}"
            password: "{{ cert.resources.0.data.password | default('') | b64decode }}"
            privateKey: "{{ cert.resources.0.data['tls.key'] | default('') | b64decode }}"
            publicCert: "{{ cert.resources.0.data['tls.crt'] | default('') | b64decode }}"

      - name: update spec
        set_fact:
          spec: "{{ spec | default({}) | combine({ 'desiredState':{ desiredState }}, recursive=True) }}"

      when: spec.secret is defined

...

