---

    - name: Setup the Component environment
      set_fact:
        nginx_lb_namespace: "{{ item.metadata.namespace }}"
        component_name: "{{ item.metadata.name }}"
        spec: "{{ item.spec }}"
        controller: "{{ item.spec.controller }}"
        # Reset the pod_selectors and node_ips from previous loops
        pod_selectors: []
        node_ips: []

    - name: Setup Connection to Controller
      include_tasks: tasks/setup_env.yml

    - name: Setup the Component
      include_tasks: tasks/component.yml

