# permissions for end users to edit certificates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificate-editor-role
rules:
- apiGroups:
  - lb.nginx.com
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lb.nginx.com
  resources:
  - certificates/status
  verbs:
  - get
