# permissions for end users to edit components.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: component-editor-role
rules:
- apiGroups:
  - lb.nginx.com
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lb.nginx.com
  resources:
  - components/status
  verbs:
  - get
