apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificates.lb.nginx.com
spec:
  group: lb.nginx.com
  names:
    kind: Certificate
    listKind: CertificateList
    plural: certificates
    singular: certificate
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
      properties:
        controller:
          type: string
        displayName:
          type: string
        description:
          type: string
        desiredState:
          type: object
        secret:
          type: string


  versions:
  - name: v1alpha1
    served: true
    storage: true
