apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.lb.nginx.com
spec:
  group: lb.nginx.com
  names:
    kind: Component
    listKind: ComponentList
    plural: components
    singular: component
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
      properties:
        controller:
          type: string
        application:
          type: string
        gateway:
          type: string
        ingress:
          type: string
        workload:
          type: object
          properties:
            scheme:
              type: string
            path:
              type: string
            targetPort:
              type: integer
            crcOverride:
              type: string
        displayName:
          type: string
        description:
          type: string
        desiredState:
          type: object

  versions:
  - name: v1alpha1
    served: true
    storage: true
