apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.lb.nginx.com
spec:
  group: lb.nginx.com
  names:
    kind: Gateway
    listKind: GatewayList
    plural: gateways
    singular: gateway
  scope: Namespaced
  subresources:
    status: {}
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this resource'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents.'
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            controller:
              type: string
            displayName:
              type: string
            description:
              type: string
            certificate:
              type: string
            desiredState:
              x-kubernetes-preserve-unknown-fields: true
              type: object

  versions:
  - name: v1alpha1
    served: true
    storage: true
