apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applications.lb.nginx.com
spec:
  group: lb.nginx.com
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
      properties:
        controller:
          type: string
        displayName:
          type: string
        description:
          type: string

  versions:
  - name: v1alpha1
    served: true
    storage: true
