apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.lb.nginx.com
spec:
  group: lb.nginx.com
  names:
    kind: Gateway
    listKind: GatewayList
    plural: gateways
    singular: gateway
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
      properties:
        controller:
          type: string
        displayName:
          type: string
        description:
          type: string
        desiredState:
          type: object

  versions:
  - name: v1alpha1
    served: true
    storage: true
