apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: controllers.lb.nginx.com
spec:
  group: lb.nginx.com
  names:
    kind: Controller
    listKind: ControllerList
    plural: controllers
    singular: controller
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
      properties:
        spec:
          type: object
          properties:
            user_email:
              type: string
            secret:
              type: string
            fqdn:
              type: string
            environmentname:
              type: string
            validate_certs:
              type: boolean
  versions:
  - name: v1alpha1
    served: true
    storage: true

