kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-lb-operator
subjects:
- kind: ServiceAccount
  name: nginx-lb-operator
  namespace: nginx-lb
roleRef:
  kind: ClusterRole
  name: nginx-lb-operator
  apiGroup: rbac.authorization.k8s.io
