# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/lb.nginx.com_controllers.yaml
- bases/lb.nginx.com_applications.yaml
- bases/lb.nginx.com_components.yaml
- bases/lb.nginx.com_gateways.yaml
- bases/lb.nginx.com_certificates.yaml
#+kubebuilder:scaffold:crdkustomizeresource
