apiVersion: lb.nginx.com/v1alpha1
kind: Component
metadata:
  name: whatcheese-web
  namespace: simple-cheese-demo
  labels:
    # echo -n whatcheese-web.simple-cheese-demo | sha224sum
    deployment-hash: 95cf698e1f1f8c7a491c4a04787a0128948a19c5683d71deeec4006a
spec:
  # Add fields here
  controller: "dev-controller"
  application: "whatcheese"
  ingressType: "Service"
  ingressName: "whatcheese-web"
  gateway: "whatcheese-gw"
  workload:
    scheme: "http"
    path: "/"
    targetPort: 80
  displayName: "Whatcheese Web"
  description: "The main Website"
  desiredState:
    backend:
      monitoring:
        response:
          status:
            match: true
            range:
              endCode: 302
              startCode: 200
        uri: /
      workloadGroups:
        # group uris will be populated from "ingress" pods or nodeports
        group:
          loadBalancingMethod:
            type: ROUND_ROBIN
    # ingress gatewayRefs will be populated from "gateway"
    ingress:
      uris:
        /: {}
