apiVersion: lb.nginx.com/v1alpha1
kind: Component
metadata:
  name: whatcheese-api
  namespace: simple-cheese-demo
  labels:
    deployment: whatcheese-web.simple-cheese-demo
spec:
  # Add fields here
  controller: "dev-controller"
  application: "whatcheese"
  ingressService: "whatcheese-api"
  gateway: "whatcheese-gw"
  workload:
    scheme: "http"
    path: "/v1"
    targetPort: 80
  displayName: "Whatcheese API"
  description: "The Cheese API"
  desiredState:
    backend:
      monitoring:
        response:
          status:
            match: true
            range:
              startCode: 200
              endCode: 200
        uri: /v1/links
      workloadGroups:
        # group uris will be populated from "ingress" pods or nodeports
        group:
          loadBalancingMethod:
            type: ROUND_ROBIN
    # ingress gatewayRefs will be populated from "gateway"
    ingress:
      uris:
        /v1: {}
    programmability:
      uriRewrites:
        - incomingPattern: "^/api/v1(.*)"
          rewritePattern: "/v1$1"
    security:
      rateLimit:
        defaultLimit:
          rate: 5
          rateMeasure: SECONDS
          statusCode: 429
          key: "$binary_remote_addr"

