---
- hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - community.kubernetes
    - operator_sdk.util
    - nginxinc.nginx_controller
  vars:
    ansible_verbosity: "{{ lookup('env','ANSIBLE_VERBOSITY_APPLICATION_LB_NGINX_COM') }}"
    resource_type: "Application"

  tasks:

    - name: Work around Ansible snake_casing our vars
      set_fact:
        spec: "{{ _lb_nginx_com_application_spec }}"
        resource: "{{ _lb_nginx_com_application }}"

    - name: Setup Connection to Controller
      import_tasks: tasks/setup_env.yml

    - name: Dump the final sec
      debug:
        msg: "{{ spec }}"
      when: ansible_verbosity > 2

    - name: Configure the application
      include_role:
        name: nginxinc.nginx_controller.nginx_controller_application
      vars:
        nginx_controller_app:
          metadata:
            name: "{{ ansible_operator_meta.namespace ~ '.' ~ ansible_operator_meta.name }}"
            displayName: "{{ spec.displayName | default( ansible_operator_meta.namespace ~ '.' ~ ansible_operator_meta.name) }}"
            description: "{{ spec.description | default('Managed by NGINX-lb-operator') }}"
      when: delete is undefined

    - name: Remove the Application
      block:

      - name: Build Controller URL
        set_fact:
          delete_url: "https://{{ nginx_controller_fqdn }}/api/v1/services/environments/{{ nginx_controller_environmentName }}/apps/{{ ansible_operator_meta.namespace ~ '.' ~ ansible_operator_meta.name }}"

      - name: Perform deletion tasks
        import_tasks: tasks/delete.yml

      when: delete is defined

