---
- hosts: localhost
  gather_facts: yes
  collections:
    - community.kubernetes
    - operator_sdk.util
    - nginxinc.nginx_controller

  tasks:

    - name: Work around Ansible snake_casing our vars
      set_fact:
        spec: "{{ _lb_nginx_com_certificate_spec }}"

    - name: Setup Connection to Controller
      import_tasks: tasks/setup_env.yml

    - name: Perform the certificate processing
      import_tasks: tasks/certificate.yml

    - name: Configure the Certificate
      include_role:
        name: nginxinc.nginx_controller.nginx_controller_certificate
      vars:
        nginx_controller_certificate:
          metadata:
            name: "{{ meta.namespace ~ '.' ~ meta.name }}"
            displayName: "{{ spec.displayName | default( meta.namespace ~ '.' ~ meta.name) }}"
            description: "{{ spec.description | default('Managed by NGINX-lb-operator') }}"
          desiredState: "{{ finalState | default({}) }}"
      when: delete is undefined

    - name: Remove the Gateway
      block:

        - name: Build Controller URL
          set_fact:
            delete_url: "https://{{ nginx_controller_fqdn }}/api/v1/services/environments/{{ nginx_controller_environmentName }}/certs/{{ meta.namespace ~ '.' ~ meta.name }}"

        - name: Perform deletion tasks
          import_tasks: tasks/delete.yml

      when: delete is defined


