---
- hosts: localhost
  gather_facts: yes
  collections:
    - community.kubernetes
    - operator_sdk.util
    - nginxinc.nginx_controller

  tasks:

    - name: Work around Ansible snake_casing our vars
      set_fact:
        spec: "{{ _lb_nginx_com_component_spec }}"

    - name: Setup Connection to Controller
      import_tasks: tasks/setup_env.yml

    - name: Get the workgroups
      import_tasks: tasks/workgroups.yml

    - name: set the gatewayRefs
      set_fact:
        finalState: "{{ finalState | default({}) | combine( { 'ingress':{ 'gatewayRefs': [ { 'ref': '/services/environments/' ~ nginx_controller_environmentName ~ '/gateways/' ~ meta.namespace ~ '.' ~ spec.gateway } ] }}, recursive=True) }}"

    - name: Configure the Component
      include_role:
        name: nginxinc.nginx_controller.nginx_controller_component
      vars:
        nginx_controller_appName: "{{ meta.namespace ~ '.' ~ spec.application }}"
        nginx_controller_component:
          metadata:
            name: "{{ meta.namespace ~ '.' ~ meta.name }}"
            displayName: "{{ spec.displayName | default( meta.namespace ~ '.' ~ meta.name) }}"
            description: "{{ spec.description | default('Managed by NGINX-lb-operator') }}"
          desiredState: "{{ finalState | default({}) }}"
      when: delete is undefined

    - name: Remove the Component
      block:

        - name: Build Controller URL
          set_fact:
            delete_url: "https://{{ nginx_controller_fqdn }}/api/v1/services/environments/{{ nginx_controller_environmentName }}/apps/{{ meta.namespace ~ '.' ~ spec.application }}/components/{{ meta.namespace ~ '.' ~ meta.name }}"

        - name: Perform deletion tasks
          import_tasks: tasks/delete.yml

      when: delete is defined

