---
- hosts: localhost
  gather_facts: yes
  connection: local
  collections:
    - community.kubernetes
    - operator_sdk.util
    - nginxinc.nginx_controller
  vars:
    ansible_verbosity: "{{ lookup('env','ANSIBLE_VERBOSITY_COMPONENT_LB_NGINX_COM') }}"
    resource_type: "Component"

  tasks:

    - name: Work around Ansible snake_casing our vars
      set_fact:
        spec: "{{ _lb_nginx_com_component_spec }}"

    - name: Setup Connection to Controller
      import_tasks: tasks/setup_env.yml

    - name: Configure the Component
      block: 
    
      - name: Setup the Component
        import_tasks: tasks/component.yml

      when: delete is undefined

    - name: Remove the Component
      block:

      - name: Build Controller URL
        set_fact:
          delete_url: "https://{{ nginx_controller_fqdn }}/api/v1/services/environments/{{ nginx_controller_environmentName }}/apps/{{ meta.namespace ~ '.' ~ spec.application }}/components/{{ meta.name }}"

      - name: Perform deletion tasks
        import_tasks: tasks/delete.yml

      when: delete is defined

