---
- hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - community.kubernetes
    - operator_sdk.util
    - nginxinc.nginx_controller
  vars:
    #ansible_verbosity: "{{ lookup('env','ANSIBLE_VERBOSITY_CONTROLLER_LB_NGINX_COM') }}"
    ansible_verbosity: 2
    resource_type: "Controller"

  tasks:

    - name: Work around Ansible snake_casing our vars
      set_fact:
        spec: "{{ _lb_nginx_com_controller_spec }}"
        resource: "{{ _lb_nginx_com_controller }}"

    - name: Setup Connection to Controller
      import_tasks: tasks/setup_env.yml

    - name: Remove the Controller
      block:

      - name: Set the controller Auth cache file
        set_fact:
          token_cache: "{{ '/tmp/ctl-' ~ meta.namespace ~ '/' ~ meta.namespace ~ '.' ~ meta.name ~ '_' ~ spec.secret ~ '.auth' }}"

      - name: Remove cached credentials
        file:
          path: "{{ token_cache }}"
          state: absent

      when: delete is defined

