---
- hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - community.kubernetes
    - operator_sdk.util
    - nginxinc.nginx_controller
  vars:
    ansible_verbosity: "{{ lookup('env','ANSIBLE_VERBOSITY_DEPLOYMENT_APPS') }}"
    resource_type: "Deployment"
    watch_namespace: "{{ lookup('env','WATCH_NAMESPACE')  }}"

  tasks:

    - name: Work around Ansible snake_casing our vars
      set_fact:
        spec: "{{ _apps_deployment_spec }}"
        resource: "{{ _apps_deployment }}"

    - name: Dump the Resource
      debug:
        msg: "{{ resource }}"
      when: ansible_verbosity > 2

    - name: Wait for Kubernetes to complete pod changes
      k8s_info:
        kind: Deployment
        api_version: v1
        name: "{{ meta.name }}"
        namespace: "{{ meta.namespace }}"
      register: deployment_status
      until: (deployment_status.resources is defined) and
             (deployment_status.resources.0.spec.replicas  == (deployment_status.resources.0.status.availableReplicas | default(0)) )
      retries: 10
      delay: 2
      ignore_errors: true

    # Set the namespace for component lookup. Empty when namespace is empty or multiple and
    # the current namespace when it consists of just one element.
    - name: Set Lookup NameSpace
      set_fact:
        lookup_namespace: "{{ watch_namespace }}"
      when: ( watch_namespace != "" ) and ((',' in watch_namespace) == False)

    - name: Get the Components
      k8s_info:
        kind: Component
        api_version: lb.nginx.com/v1alpha1
        namespace: "{{ lookup_namespace | default('') }}"
        label_selectors:
          - "deployment-hash = {{ ( meta.name ~ '.' ~ meta.namespace ) | hash('sha224') }}"
      register: components

    - name: Filter watched components
      set_fact:
        filtered_components: "{{ components | json_query( filter_components ) }}"
      with_dict: "{{ components }}"
      vars:
        filter_components: "resources[? contains( '{{ watch_namespace }}', @.metadata.namespace) ]"
      when: watch_namespace != ""

    - name: Update the Components list
      set_fact:
        components: "{{ filtered_components | default( components.resources ) }}"

    - name: Dump the Components
      debug:
        msg: "{{ components }}"
      when: ansible_verbosity > 2

    - name: Update all Components with labels linked to this deployment
      include_tasks: tasks/component_loop.yml
      with_list: "{{ components }}"
      loop_control:
        loop_var: component_loop_item
      when: components | length > 0

