---
- hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - community.kubernetes
    - operator_sdk.util
    - nginxinc.nginx_controller
  vars:
    ansible_verbosity: "{{ lookup('env','ANSIBLE_VERBOSITY_DEPLOYMENT_APPS') }}"
    resource_type: "Deployment"

  tasks:

    - name: Work around Ansible snake_casing our vars
      set_fact:
        spec: "{{ _apps_deployment_spec }}"
        resource: "{{ _apps_deployment }}"

    - name: End Play if label not set
      block:

        - name: Ending Playbook
          debug:
            msg: This Deployment has no 'nginx-lb-component' label

        - meta: end_play

      when: ( resource.metadata.labels is undefined ) or
            ( resource.metadata.labels["nginx-lb-component"] is undefined )

    - name: Dump the Resource
      debug:
        msg: "{{ resource }}"
      when: ansible_verbosity > 2

    - name: Brief Pause
      pause:
        seconds: 2

    - name: Wait for Kubernetes to complete pod changes
      k8s:
        kind: Deployment
        api_version: v1
        name: "{{ meta.name }}"
        namespace: "{{ meta.namespace }}"
      register: deployment_status
      until: (deployment_status.result is defined) and
             (deployment_status.result.spec.replicas == deployment_status.result.status.availableReplicas )
      retries: 10
      delay: 2

    - name: "Store the component name"
      set_fact:
        nginx_lb_component: "{{  resource.metadata.labels['nginx-lb-component'] }}"
      when: ( resource.metadata.labels is defined ) and
            ( resource.metadata.labels["nginx-lb-component"] is defined )

    - name: Get and Update the Component
      block:

      - name: Get the Component
        k8s_info:
          kind: Component
          api_version: lb.nginx.com/v1alpha1
          name: "{{ resource.metadata.labels['nginx-lb-component'] }}"
          namespace: "{{ meta.namespace }}"
        register: component

      - name: Dump the Component
        debug:
          msg: "{{ component }}"
        when: ansible_verbosity > 2

      - name: Perform the Component update 
        block:

        - name: setup component environment
          set_fact:
            meta:
              name: "{{ component.resources.0.metadata.name }}"
              namespace: "{{ component.resources.0.metadata.namespace }}"
            spec: "{{ component.resources.0.spec }}"
            controller: "{{ component.resources.0.spec.controller }}"

        - name: Setup Connection to Controller
          import_tasks: tasks/setup_env.yml

        - name: Setup the Component
          import_tasks: tasks/component.yml

        when: component.resources.0 is defined

      when: nginx_lb_component is defined

