---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certificates.lb.nginx.com
spec:
  group: lb.nginx.com
  names:
    kind: Certificate
    listKind: CertificateList
    plural: certificates
    singular: certificate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this resource'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents.'
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              controller:
                type: string
              displayName:
                type: string
              description:
                type: string
              desiredState:
                x-kubernetes-preserve-unknown-fields: true
                type: object
              secret:
                type: string
              secretCA: 
                type: string
    served: true
    storage: true
    subresources:
      status: {}
