---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: controllers.lb.nginx.com
spec:
  group: lb.nginx.com
  names:
    kind: Controller
    listKind: ControllerList
    plural: controllers
    singular: controller
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this resource'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents.'
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              user_email:
                type: string
              secret:
                type: string
              fqdn:
                type: string
              environment:
                type: string
              validate_certs:
                type: boolean
    served: true
    storage: true
    subresources:
      status: {}
